name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"] # run this when you push to main branch
  workflow_dispatch: # allows you to run it manually in GitHub

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Node.js version
      - run: npm ci # install dependencies
      - run: npm run predeploy # build + export your Next.js site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # this is your static site folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
